spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health
